# /// script
# /// requires-python = ">=3.10"
# /// dependencies = [
# ///   "ultralytics>=8.2.0",
# ///   "pyyaml>=6.0",
# ///   "rich>=13.0",
# ///   "opencv-python-headless>=4.8.0",
# ///   "Pillow>=10.0",
# ///   "albumentations>=1.4.0",
# /// ]
# /// [tool.uv]
# /// exclude-newer = "2026-06-01"
# ///
# ──────────────────────────────────────────────────────────────────────────────
# yolo_data_prep.py — Dataset Preparation & Annotation Pipeline
# ──────────────────────────────────────────────────────────────────────────────
#
# Automates the creation, validation, and augmentation of a YOLO-format face
# detection dataset from raw image collections. Handles:
#
#   1. Directory scaffolding  — Creates the expected train/val/images/labels
#      folder structure.
#   2. Train/val splitting    — Splits a flat image+label directory into
#      stratified train and validation sets.
#   3. Annotation conversion  — Converts COCO JSON or Pascal VOC XML labels
#      to YOLO normalised `.txt` format.
#   4. Offline augmentation   — Generates augmented copies of training images
#      with geometrically consistent bbox transforms.
#   5. Dataset statistics     — Prints a summary of class distributions,
#      image counts, and bbox size histograms.
#
# Usage:
#     uv run scripts/yolo_data_prep.py scaffold
#     uv run scripts/yolo_data_prep.py split --source ./raw_faces/ --ratio 0.2
#     uv run scripts/yolo_data_prep.py convert --format coco --input annotations.json
#     uv run scripts/yolo_data_prep.py augment --multiplier 3
#     uv run scripts/yolo_data_prep.py stats
# ──────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import argparse
import random
import shutil
import sys
from pathlib import Path

# ── Ensure scripts/ is on sys.path ──────────────────────────────────────────
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from utils.config import YoloConfig
from utils.logging_setup import setup_logger
from utils.data_transforms import coco_to_yolo, voc_to_yolo


# ═══════════════════════════════════════════════════════════════════════════════
# §1  Sub-command: scaffold
# ═══════════════════════════════════════════════════════════════════════════════

def cmd_scaffold(args: argparse.Namespace, cfg: YoloConfig, logger) -> None:
    """Create the canonical YOLO dataset directory structure.

    This generates the following tree under ``cfg.data_dir``::

        datasets/faces/
        ├── data.yaml
        ├── train/
        │   ├── images/
        │   └── labels/
        └── val/
            ├── images/
            └── labels/

    The ``data.yaml`` file is auto-populated with a single ``face`` class
    and relative paths. Edit it manually if your dataset has multiple classes.
    """
    data_dir = cfg.data_dir
    logger.info("Scaffolding dataset directory: %s", data_dir)

    # Create directory tree.
    for split in ("train", "val"):
        for subdir in ("images", "labels"):
            (data_dir / split / subdir).mkdir(parents=True, exist_ok=True)

    # Generate a starter data.yaml if it doesn't exist.
    data_yaml = data_dir / "data.yaml"
    if not data_yaml.exists():
        yaml_content = (
            f"# YOLOv8 Dataset Configuration\n"
            f"# Auto-generated by yolo_data_prep.py scaffold\n"
            f"path: {data_dir.resolve()}\n"
            f"train: train/images\n"
            f"val: val/images\n"
            f"\n"
            f"# Class definitions (edit as needed)\n"
            f"names:\n"
            f"  0: face\n"
        )
        data_yaml.write_text(yaml_content, encoding="utf-8")
        logger.info("Created data.yaml with 1 class: face")
    else:
        logger.info("data.yaml already exists — skipping creation.")

    logger.info("Dataset scaffold complete. Place your images and labels into:")
    logger.info("  train: %s", data_dir / "train")
    logger.info("  val:   %s", data_dir / "val")


# ═══════════════════════════════════════════════════════════════════════════════
# §2  Sub-command: split
# ═══════════════════════════════════════════════════════════════════════════════

SUPPORTED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def cmd_split(args: argparse.Namespace, cfg: YoloConfig, logger) -> None:
    """Split a flat image+label directory into train and validation sets.

    Expects the source directory to contain image files alongside
    identically-named ``.txt`` label files. Files are shuffled with
    a fixed seed and split according to ``--ratio`` (fraction for val).

    Args (from CLI):
        --source:  Path to the flat directory of images + labels.
        --ratio:   Fraction of files to allocate to the validation set
                   (default: 0.2 = 20%).
        --seed:    Random seed for reproducible shuffling.
    """
    source = Path(args.source)
    if not source.is_dir():
        logger.error("Source directory not found: %s", source)
        sys.exit(1)

    # ── Collect image files ──────────────────────────────────────────────
    image_files = sorted(
        f for f in source.iterdir()
        if f.suffix.lower() in SUPPORTED_EXTENSIONS
    )

    if not image_files:
        logger.error("No images found in %s", source)
        sys.exit(1)

    # ── Shuffle and split ────────────────────────────────────────────────
    random.seed(args.seed)
    random.shuffle(image_files)

    val_count = max(1, int(len(image_files) * args.ratio))
    val_files = image_files[:val_count]
    train_files = image_files[val_count:]

    logger.info("Splitting %d images → %d train + %d val", len(image_files), len(train_files), len(val_files))

    # ── Copy files into the scaffolded structure ─────────────────────────
    data_dir = cfg.data_dir

    for split_name, file_list in [("train", train_files), ("val", val_files)]:
        img_dir = data_dir / split_name / "images"
        lbl_dir = data_dir / split_name / "labels"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)

        for img_path in file_list:
            # Copy image.
            shutil.copy2(img_path, img_dir / img_path.name)

            # Copy matching label file if it exists.
            label_path = img_path.with_suffix(".txt")
            if label_path.exists():
                shutil.copy2(label_path, lbl_dir / label_path.name)
            else:
                # Create an empty label (negative sample — no detections).
                (lbl_dir / label_path.name).write_text("", encoding="utf-8")
                logger.debug("No label for %s — created empty negative sample.", img_path.name)

    logger.info("Split complete. Files copied to: %s", data_dir)


# ═══════════════════════════════════════════════════════════════════════════════
# §3  Sub-command: convert
# ═══════════════════════════════════════════════════════════════════════════════

def cmd_convert(args: argparse.Namespace, cfg: YoloConfig, logger) -> None:
    """Convert annotations from COCO JSON or Pascal VOC XML to YOLO format.

    The converted ``.txt`` label files are written to the train/labels
    directory by default.

    Args (from CLI):
        --format:       Source annotation format ('coco' or 'voc').
        --input:        Path to the COCO JSON file or VOC XML directory.
        --output-dir:   Directory for the output YOLO labels.
        --class-names:  Comma-separated list of class names.
    """
    fmt = args.format.lower()
    input_path = Path(args.input)
    output_dir = Path(args.output_dir) if args.output_dir else (cfg.data_dir / "train" / "labels")
    class_names = [c.strip() for c in args.class_names.split(",")] if args.class_names else ["face"]

    logger.info("Converting %s → YOLO format", fmt.upper())
    logger.info("Classes: %s", class_names)

    if fmt == "coco":
        if not input_path.is_file():
            logger.error("COCO JSON file not found: %s", input_path)
            sys.exit(1)
        stats = coco_to_yolo(input_path, output_dir, class_names=class_names)
    elif fmt == "voc":
        if not input_path.is_dir():
            logger.error("VOC XML directory not found: %s", input_path)
            sys.exit(1)
        stats = voc_to_yolo(input_path, output_dir, class_names=class_names)
    else:
        logger.error("Unsupported format: '%s'. Use 'coco' or 'voc'.", fmt)
        sys.exit(1)

    logger.info("Conversion stats: %s", stats)


# ═══════════════════════════════════════════════════════════════════════════════
# §4  Sub-command: augment
# ═══════════════════════════════════════════════════════════════════════════════

def cmd_augment(args: argparse.Namespace, cfg: YoloConfig, logger) -> None:
    """Generate augmented copies of training images with consistent bbox transforms.

    For each training image, this creates ``--multiplier`` augmented variants
    (default: 3). Both the augmented image and its transformed labels are
    saved alongside the originals.

    This is an offline augmentation step. Ultralytics also supports online
    augmentation during training (the default), so this command is optional
    and useful for small datasets where you want to inflate the training set.

    Args (from CLI):
        --multiplier:  Number of augmented copies per original image (default: 3).
        --image-size:  Target resolution for the augmentation pipeline.
    """
    import cv2
    import numpy as np
    from utils.data_transforms import build_augmentation_pipeline

    train_img_dir = cfg.data_dir / "train" / "images"
    train_lbl_dir = cfg.data_dir / "train" / "labels"

    if not train_img_dir.exists():
        logger.error("Training images directory not found: %s", train_img_dir)
        sys.exit(1)

    # ── Build augmentation pipeline ──────────────────────────────────────
    pipeline = build_augmentation_pipeline(image_size=args.image_size)

    # ── Collect original images ──────────────────────────────────────────
    image_files = sorted(
        f for f in train_img_dir.iterdir()
        if f.suffix.lower() in SUPPORTED_EXTENSIONS and "_aug" not in f.stem
    )

    logger.info(
        "Augmenting %d images × %d = %d new samples",
        len(image_files), args.multiplier, len(image_files) * args.multiplier,
    )

    created = 0
    for img_path in image_files:
        # Read image.
        img = cv2.imread(str(img_path))
        if img is None:
            logger.warning("Could not read image: %s", img_path.name)
            continue
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Read YOLO labels.
        label_path = train_lbl_dir / (img_path.stem + ".txt")
        bboxes: list[list[float]] = []
        class_labels: list[int] = []

        if label_path.exists():
            for line in label_path.read_text(encoding="utf-8").strip().splitlines():
                parts = line.strip().split()
                if len(parts) >= 5:
                    class_labels.append(int(parts[0]))
                    bboxes.append([float(v) for v in parts[1:5]])

        # Generate augmented copies.
        for aug_idx in range(args.multiplier):
            try:
                augmented = pipeline(
                    image=img_rgb,
                    bboxes=bboxes,
                    class_labels=class_labels,
                )
            except Exception as exc:
                logger.debug("Augmentation failed for %s (variant %d): %s", img_path.name, aug_idx, exc)
                continue

            aug_img = augmented["image"]
            aug_bboxes = augmented["bboxes"]
            aug_labels = augmented["class_labels"]

            # Save augmented image.
            aug_stem = f"{img_path.stem}_aug{aug_idx}"
            aug_img_path = train_img_dir / f"{aug_stem}{img_path.suffix}"
            cv2.imwrite(str(aug_img_path), cv2.cvtColor(aug_img, cv2.COLOR_RGB2BGR))

            # Save augmented labels.
            aug_lbl_path = train_lbl_dir / f"{aug_stem}.txt"
            lines = []
            for cls, bbox in zip(aug_labels, aug_bboxes):
                lines.append(f"{cls} {bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}")
            aug_lbl_path.write_text("\n".join(lines), encoding="utf-8")

            created += 1

    logger.info("Augmentation complete: %d new samples created.", created)


# ═══════════════════════════════════════════════════════════════════════════════
# §5  Sub-command: stats
# ═══════════════════════════════════════════════════════════════════════════════

def cmd_stats(args: argparse.Namespace, cfg: YoloConfig, logger) -> None:
    """Print a statistical summary of the dataset.

    Reports:
        • Total image count per split (train / val).
        • Total annotation count per split.
        • Class distribution (how many bboxes per class).
        • Bounding box size statistics (mean, min, max width/height).
    """
    data_dir = cfg.data_dir

    for split in ("train", "val"):
        img_dir = data_dir / split / "images"
        lbl_dir = data_dir / split / "labels"

        if not img_dir.exists():
            logger.warning("Missing split: %s", img_dir)
            continue

        images = [f for f in img_dir.iterdir() if f.suffix.lower() in SUPPORTED_EXTENSIONS]
        labels = list(lbl_dir.glob("*.txt")) if lbl_dir.exists() else []

        # Parse all label files to collect class and size statistics.
        class_counts: dict[int, int] = {}
        widths: list[float] = []
        heights: list[float] = []
        total_bboxes = 0

        for lbl_file in labels:
            for line in lbl_file.read_text(encoding="utf-8").strip().splitlines():
                parts = line.strip().split()
                if len(parts) < 5:
                    continue
                cls_id = int(parts[0])
                w, h = float(parts[3]), float(parts[4])

                class_counts[cls_id] = class_counts.get(cls_id, 0) + 1
                widths.append(w)
                heights.append(h)
                total_bboxes += 1

        # ── Print summary ────────────────────────────────────────────────
        logger.info("─── %s split ───", split.upper())
        logger.info("  Images:      %d", len(images))
        logger.info("  Label files: %d", len(labels))
        logger.info("  Bounding boxes: %d", total_bboxes)

        if class_counts:
            logger.info("  Class distribution:")
            for cls_id in sorted(class_counts):
                logger.info("    class %d: %d boxes", cls_id, class_counts[cls_id])

        if widths:
            logger.info("  BBox widths  — mean: %.4f, min: %.4f, max: %.4f", 
                        sum(widths)/len(widths), min(widths), max(widths))
            logger.info("  BBox heights — mean: %.4f, min: %.4f, max: %.4f",
                        sum(heights)/len(heights), min(heights), max(heights))


# ═══════════════════════════════════════════════════════════════════════════════
# §6  Main Entry Point
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    """Parse sub-commands and dispatch to the appropriate handler."""
    parser = argparse.ArgumentParser(
        prog="yolo_data_prep",
        description="Dataset preparation tools for the YOLO face-detection pipeline.",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging.")
    parser.add_argument(
        "--data-dir", type=Path, default=None,
        help="Dataset root directory. Defaults to <project_root>/datasets/faces.",
    )

    subparsers = parser.add_subparsers(dest="command", help="Sub-command to execute.")

    # ── scaffold ─────────────────────────────────────────────────────────
    subparsers.add_parser("scaffold", help="Create the dataset directory structure.")

    # ── split ────────────────────────────────────────────────────────────
    split_parser = subparsers.add_parser("split", help="Split images into train/val sets.")
    split_parser.add_argument("--source", type=str, required=True, help="Source directory of images + labels.")
    split_parser.add_argument("--ratio", type=float, default=0.2, help="Validation set ratio (default: 0.2).")
    split_parser.add_argument("--seed", type=int, default=42, help="Random seed (default: 42).")

    # ── convert ──────────────────────────────────────────────────────────
    conv_parser = subparsers.add_parser("convert", help="Convert COCO/VOC annotations to YOLO format.")
    conv_parser.add_argument("--format", type=str, required=True, choices=["coco", "voc"], help="Source format.")
    conv_parser.add_argument("--input", type=str, required=True, help="Input file (COCO JSON) or directory (VOC XML).")
    conv_parser.add_argument("--output-dir", type=str, default=None, help="Output directory for YOLO labels.")
    conv_parser.add_argument("--class-names", type=str, default="face", help="Comma-separated class names.")

    # ── augment ──────────────────────────────────────────────────────────
    aug_parser = subparsers.add_parser("augment", help="Generate augmented training samples.")
    aug_parser.add_argument("--multiplier", type=int, default=3, help="Augmented copies per image (default: 3).")
    aug_parser.add_argument("--image-size", type=int, default=640, help="Target resolution (default: 640).")

    # ── stats ────────────────────────────────────────────────────────────
    subparsers.add_parser("stats", help="Print dataset statistics.")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    cfg = YoloConfig(data_dir=args.data_dir, verbose=args.verbose)
    logger = setup_logger(verbose=cfg.verbose)

    # Dispatch to the correct sub-command handler.
    dispatch = {
        "scaffold": cmd_scaffold,
        "split": cmd_split,
        "convert": cmd_convert,
        "augment": cmd_augment,
        "stats": cmd_stats,
    }
    dispatch[args.command](args, cfg, logger)


if __name__ == "__main__":
    main()
